[project]
name = "waste-management-system"
authors = ["Waste Management Team"]
description = "AI-powered waste management system on Stacks blockchain"
telemetry = false
requirements = []
boot_contracts = []
costs_version = 2

[contracts.waste-collection]
path = "contracts/waste-collection.clar"
clarity_version = 2
epoch = 2.1

[contracts.route-optimizer]
path = "contracts/route-optimizer.clar"
clarity_version = 2
epoch = 2.1

[contracts.waste-tracking]
path = "contracts/waste-tracking.clar"
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
